### ISSUE TITLE
Sorald throws (and catches) exceptions during repair

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/sorald#348]
@slarse I think you are aware of most of these, but here is a list of common types of crashes that we face:

[Crash in sorald.processor.IteratorNextExceptionProcessor::process](https://raw.githubusercontent.com/khaes-kth/Sorald-experiments/master/repair-results/joshua/repair-2272.json)

[Crash in sorald.processor.CastArithmeticOperandProcessor::process](https://raw.githubusercontent.com/khaes-kth/Sorald-experiments/master/repair-results/jMetal/repair-2184.json)

[Crash in sorald.processor.InterruptedExceptionProcessor::process](https://github.com/khaes-kth/Sorald-experiments/blob/master/repair-results/aesh/repair-2142.json)

[Crash in sorald.processor.UnclosedResourcesProcessor::process](https://github.com/khaes-kth/Sorald-experiments/blob/master/repair-results/aesh/repair-2095.json)

**Comment by slarse** [comment]
I think we only have open issues for `sorald.processor.CastArithmeticOperandProcessor::process` (#125). I'll have a look at the others this week.

**Comment by slarse** [comment]
I can't reproduce 
[Crash in sorald.processor.IteratorNextExceptionProcessor::process](https://raw.githubusercontent.com/khaes-kth/Sorald-experiments/master/repair-results/joshua/repair-2272.json)

I don't experience that crash, neither if I do targeted repair for that violation nor if I do all repairs for that key. There are also no other violations in that file, so it can't be down to the order of repairs. @khaes-kth can you try to run it and see if you get a crash?

**Comment by slarse** [comment]
Oh wait, all of these crashes are caused by the same thing (not the processors). It's this:

```
at sorald.UniqueTypesCollector.checkIfThereIsTheSameClassInTheOriginalPath(UniqueTypesCollector.java:59)
```

**Comment by slarse** [comment]
The `UniqueTypesCollector` is badly broken. I'm very surprised this has even been working. PR coming up.

**Comment by slarse** [comment]
I got a bit distracted by other things, but I now have a working solution for this. To clarify the problem, it's this method in the `UniqueTypesCollector`:

https://github.com/SpoonLabs/sorald/blob/da98ae47970b13d1c43fa70603e9e55cc3778c8e/src/main/java/sorald/UniqueTypesCollector.java#L53-L70

This method is supposed to resolve a problem that occurs when multiple processors act on the same file `A` when running in `CHANGED_ONLY` output mode. In that case, the first processor will operate on `A` when it's in the original source directory, which is then printed to the intermediate spoon directory (a temporary workdir). The next processor will then operate on the copied version of `A`, but when collecting that type, there will be a duplicate entry of `A` in the original source directory and `A` in the intermediate directory unless the original entry is removed.

That's what this method is supposed to do, but it's pretty broken. The first problem is that it never actually checks if the input file is in the intermediate directory, in which case the regex built from `filePath` just becomes garbage. This can also cause an out-of-bounds exception if the original `filePath` is shorter than the intermediate directory name.

The second larger problem is that the `filePath` regex is shortened further for each iteration, both making it increasingly incorrect, and in the end resulting in an out-of-bounds exception. I'm very surprised this has worked as well as it has, because it's not at all correct.
