### ISSUE TITLE
security / vulnerability warnings to implement in Sorald

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#51]
at some point, we'll need to prioritize the warnings to repair. on this topic, see

"Developer-Driven Code Smell Prioritization" https://fabiano-pecorelli.github.io/publications/conferences/C7.pdf

**Comment by slarse** [comment]
@monperrus We're about to get to the point where it's appropriate to start implementing new processors, and I've been looking specifically at vulnerabilities. 

Before I dive deeper into that, I just want your opinion on an issue. SonarQube appears to "cross-classify" many minor vulnerabilities as code smells. For example, if I look for vulnerabilities in a project, [this rule often pops up](https://sonarcloud.io/project/issues?id=apache_struts&open=AW_X5CrW1FYS5oU8LTdB&resolved=false&rules=java%3AS1444&types=VULNERABILITY). Note how it's classified as a vulnerability in the list to the left.

However, when I later go to look up the details of the rule, [it's classified as a code smell](https://rules.sonarsource.com/java/RSPEC-1444). Should we count such rules as vulnerabilities?

**Comment by slarse** [comment]
I've composed a list of "pure" vulnerability rules that I think are good candidates for sorald to fix. There are many encryption-scheme rules that I think would be relatively simple to fix with templating. The list is in no particular order, and I haven't made any attempt yet to find out how common any of these are in practice.

* [5542: Encryption algorithms should be used with secure mode and padding scheme](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-5542)
* [5547: Cipher algorithms should be robust](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-5547)
    - I'm not quite sure what differentiates this one from 5542
* [4432: AES encryption algorithm should be used with secured mode](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4432)
    - Again, not quite sure what differentiates this one from 5547 and 5542.
* [2277: Cryptographic RSA algorithms should always incorporate OAEP (Optimal Asymmetric Encryption Padding)](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2277)
* [2070: SHA-1 and Message-Digest hash algorithms should not be used in secure contexts](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2070)
* [4434: LDAP deserialization should be disabled](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4434)
* [4426: Cryptographic keys should be robust](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4426)
* [3751: "@RequestMapping" methods should be "public"](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-3751)
* [4601: "HttpSecurity" URL patterns should be correctly ordered](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4601)
* [4347: "SecureRandom" seeds should not be predictable](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4347)
* [2653: Web applications should not have a "main" method](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2653)
* [5679: OpenSAML2 should be configured to prevent authentication bypass](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-5679)
* [4423: Weak SSL/TLS protocols should not be used](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4423)
* [2278: Neither DES (Data Encryption Standard) nor DESede (3DES) should be used](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2278)
* [4499: SMTP SSL connection should check server identity](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4499)

Here is a further list that I think may be viable, but could be tricky due to their open-ended nature.

* [3649: Database queries should not be vulnerable to injection attacks](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-3649)
* [2091: XPath expressions should not be vulnerable to injection attacks](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2091)
* [5145: Logging should not be vulnerable to injection attacks](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-5145)
* [1989: Exceptions should not be thrown from servlet methods](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-1989)
* [4435:  XML transformers should be secured ](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4435)
* [2384: Mutable members should not be stored or returned directly](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2384)
    - This one is essentially impossible to solve completely with a template-based solution. But it could be solved partially for the most common types, such as arrays and various types of collections.

**Comment by monperrus** [comment]
This list looks really good, thanks @slarse. We would simply order it by 
prevalence in practice in order to maximize potential impact.

Trying to tackle some open-ended ones is excellent to identify 
interesting research challenges.

**Comment by slarse** [comment]
@monperrus Any idea of how to find their prevalence in practice, other than running the warnings miner or just looking through projects manually on SonarCloud?

**Comment by monperrus** [comment]
There are some numbers in a few papers, but with little validity. I'd 
say that running the SonarJava analyzer on a handful of representative 
projects is the best way to go.

**Comment by slarse** [comment]
That seems reasonable. I think the easiest way for me to accomplish that is to first implement #158, and then use the warnings miner to scan a few projects for only vulnerabilities. That way, I get easily managed output that I can just sort. With #168 done, it should be feasible to scan quite a large sample even with my personal (not too powerful) computer.

What do you think, reasonable plan?

**Comment by monperrus** [comment]
yes, that's a good plan.

**Comment by slarse** [comment]
Just from browsing sonarcloud for an hour, I've found that [2755: XML parsers should not be vulnerable to XXE attacks](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2755) is common. Here are some examples:

* [RedHat RSP Server](https://sonarcloud.io/project/issues?id=onap_appc&resolved=false&sonarsourceSecurity=xxe&types=VULNERABILITY)
* [ONAP appc](https://sonarcloud.io/project/issues?id=onap_appc&resolved=false&sonarsourceSecurity=xxe&types=VULNERABILITY)
* [OWASP Dependency-Check](https://sonarcloud.io/project/issues?id=org.owasp%3Adependency-check-parent&resolved=false&types=VULNERABILITY)

It's a somewhat open-ended problem as there are any number of tiny variations to the situation, but I think most situations should be possible to fix with a template. I'll start working on this one so at least I've got one vulnerability processor in the works.

**Comment by monperrus** [comment]
That's good! Pushing Sorald fixes in RSP, appc and dependency-check would be an excellent achievement.

**Comment by slarse** [comment]
This looks promising, RedHat RSP has an issue to fix Sonar vulnerabilities (code-blocking link to avoid making a reference to the issue, in case we want to PR without them knowing the PR was automatically generated): `https://github.com/redhat-developer/rsp-server/issues/317`

With my experimental version of sorald, I can patch all 4 issues related to XML parsing.

**Comment by monperrus** [comment]
> I can patch all 4 issues related to XML parsing.

Nice milestone, could you give a diff?

**Comment by slarse** [comment]
Full diff:

```diff
diff --git a/framework/bundles/org.jboss.tools.rsp.launching.java/src/main/java/org/jboss/tools/rsp/internal/launching/java/util/LaunchingSupportUtils.java b/framework/bundles/org.jboss.tools.rsp.launching.java/src/main/java/org/jboss/tools/rsp/internal/launching/java/util/LaunchingSupportUtils.java
index 26e318d6..c84cdfac 100644
--- a/framework/bundles/org.jboss.tools.rsp.launching.java/src/main/java/org/jboss/tools/rsp/internal/launching/java/util/LaunchingSupportUtils.java
+++ b/framework/bundles/org.jboss.tools.rsp.launching.java/src/main/java/org/jboss/tools/rsp/internal/launching/java/util/LaunchingSupportUtils.java
@@ -6,7 +6,7 @@
  * 
  * Contributors: Red Hat, Inc.
  ******************************************************************************/
-package org.jboss.tools.rsp.internal.launching.java.util;
+package org.jboss.tools.rsp.internal.launching.java.util;import javax.xml.XMLConstants;
 
 import java.io.ByteArrayInputStream;
 import java.io.File;
@@ -82,7 +82,7 @@ public class LaunchingSupportUtils {
        private static DocumentBuilder getParser() throws CoreException {
                if (fgXMLParser == null) {
                        try {
-                               fgXMLParser = DocumentBuilderFactory.newInstance().newDocumentBuilder();
+                               fgXMLParser = createDocumentBuilderFactory().newDocumentBuilder();
                                fgXMLParser.setErrorHandler(new DefaultHandler());
                        } catch (ParserConfigurationException e) {
                                abort(LaunchingPlugin_34, e);
@@ -348,4 +348,11 @@ public class LaunchingSupportUtils {
                throw new CoreException(new Status(IStatus.ERROR, IVMInstallChangedListener.LAUNCHING_ID_PLUGIN,
                                code, message, exception));
        }
+
+       private static DocumentBuilderFactory createDocumentBuilderFactory() {
+               javax.xml.parsers.DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
+               factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
+               factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
+               return factory;
+       }
 }
diff --git a/framework/bundles/org.jboss.tools.rsp.launching/src/main/java/org/jboss/tools/rsp/launching/memento/XMLMemento.java b/framework/bundles/org.jboss.tools.rsp.launching/src/main/java/org/jboss/tools/rsp/launching/memento/XMLMemento.java
index 291d3814..c4fb2711 100644
--- a/framework/bundles/org.jboss.tools.rsp.launching/src/main/java/org/jboss/tools/rsp/launching/memento/XMLMemento.java
+++ b/framework/bundles/org.jboss.tools.rsp.launching/src/main/java/org/jboss/tools/rsp/launching/memento/XMLMemento.java
@@ -89,7 +89,7 @@ public final class XMLMemento implements IMemento {
                
                Document document = null;
                try {   
-                       DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
+                       DocumentBuilderFactory factory = createDocumentBuilderFactory();
                        DocumentBuilder parser = factory.newDocumentBuilder();
                        document = parser.parse(new InputSource(in));
                        Node node = document.getFirstChild();
@@ -126,7 +126,7 @@ public final class XMLMemento implements IMemento {
        public static XMLMemento createWriteRoot(String type) {
                Document document;
                try {
-                       document = DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();
+                       document = createDocumentBuilderFactory().newDocumentBuilder().newDocument();
                        Element element = document.createElement(type);
                        document.appendChild(element);
                        return new XMLMemento(document, element);
@@ -348,7 +348,7 @@ public final class XMLMemento implements IMemento {
                Result result = new StreamResult(os);
                Source source = new DOMSource(factory);
                try {
-                       TransformerFactory factory = TransformerFactory.newInstance();
+                       TransformerFactory factory = createTransformerFactory();
                        factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
                        Transformer transformer = factory.newTransformer();
                        transformer.setOutputProperty(OutputKeys.INDENT, "yes"); //$NON-NLS-1$
@@ -436,4 +436,18 @@ public final class XMLMemento implements IMemento {
                }
                return ""; //$NON-NLS-1$
        }
+
+       private static DocumentBuilderFactory createDocumentBuilderFactory() {
+               javax.xml.parsers.DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
+               factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
+               factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
+               return factory;
+       }
+
+       private static TransformerFactory createTransformerFactory() {
+               javax.xml.transform.TransformerFactory factory = TransformerFactory.newInstance();
+               factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
+               factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
+               return factory;
+       }
 }
```

There are three things I'm not satisfied with at the moment.

1. The factory type reference in the `createTYPEFACTORY` methods is fully qualified (see #208).
2. The import added at the top of the file doesn't get a newline for some reason.
3. The `factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);` should really be removed, as it's misleading.
    - According to [2755](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2755): "Avoid FEATURE_SECURE_PROCESSING feature to protect from XXE attacks because depending on the implementation:"

I really want the patches to be "merge-ready", so to speak. I think that's really important.

**Comment by monperrus** [comment]
> The factory type reference in the createTYPEFACTORY methods is fully qualified (see #208).
> The import added at the top of the file doesn't get a newline for some reason.

Looks like Spoon problems

> I really want the patches to be "merge-ready", so to speak. 

We're 100% along the same line, that's a high priority in our project

**Comment by slarse** [comment]
> > The factory type reference in the createTYPEFACTORY methods is fully qualified (see #208).
> > The import added at the top of the file doesn't get a newline for some reason.
> 
> Looks like Spoon problems

The import not having a newline: yes, that's most likely a Spoon problem, but I haven't investigated it yet.

The may or may not be a Spoon problem, depending on how you look at it. It's caused by the fact that `setAutoImports(true)` has no effect if you define a custom pretty-printer creator, which we do for sniper printing. If I manually add the "force import"-processors in the pretty-printer creator, it works fine and the names aren't fully qualified. But there are reasons we may not want to do that, see #208 for a more detailed explanation.

**Comment by slarse** [comment]
@fermadeiral see list at the top of this issue

**Comment by monperrus** [comment]
FYI, Whitesource Cure is a commercial product which does automatic repair of vulnerabilities.
https://www.whitesourcesoftware.com/whitesource-cure/

The list of supported CWEs is at https://whitesource.atlassian.net/wiki/spaces/WD/pages/2168487982/Working+with+WhiteSource+Cure+Beta#Appendix:-Supported-CWEs

To date:

    CWE 22 - Path Traversal
    CWE 23 - Relative Path Traversal
    CWE 36 - Absolute Path Traversal
    CWE 78 - OS Command Injection
    CWE 79 - XSS - Cross Site Scripting
    CWE 80 - Basic XSS - Improper Neutralization of Script-Related HTML Tags in a Web Page
    CWE 81 - Improper Neutralization of Script in an Error Message Web Page
    CWE 83 - Improper Neutralization of Script in Attributes in a Web Page
    CWE 84 - Improper Neutralization of Encoded URI Schemes in a Web Page
    CWE 85 - Doubled Character XSS Manipulations
    CWE 86 - Improper Neutralization of Invalid Characters in Identifiers in Web Pages
    CWE 87 - Improper Neutralization of Alternate XSS Syntax
    CWE 89 - SQL Injection
    CWE 90 - LDAP Injection
    CWE 93: Improper Neutralization of CRLF Sequences ('CRLF Injection')
    CWE 113 - Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting')
    CWE 117: Improper Output Neutralization for Logs
    CWE 564 - SQL Injection - Hibernate
    CWE 614 - Sensitive Cookie in HTTPS Session Without 'Secure' Attribute
    CWE 643 - Xpath Injection
    CWE 611 - XXE - External XML Parsing
    CWE 692 - Incomplete Denylist to Cross-Site Scripting
    CWE 776 - XML Entity Expansion
    CWE 827 - Improper Control of Document Type Definition

**Comment by monperrus** [comment]
Plus the proposed repairs for Spoon: https://cure.whitesource.io/#/report/27e734061c7511ecbfde0242ac110003/cwe/22/nodeId/1/runId/25
