### ISSUE TITLE
Import wrongly removed

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/sorald#602]
When 2184 fixes are applied on [this](https://github.com/CloudburstMC/Nukkit.git) (commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60), the following change is made:

```
@@ -23,9 +23,6 @@
  */
 package co.aikar.timings;

-import static co.aikar.timings.TimingIdentifier.DEFAULT_GROUP;
-import static co.aikar.timings.TimingsManager.*;
-
 public class FullServerTickTiming extends Timing {
     private static final TimingIdentifier IDENTIFIER = new TimingIdentifier(DEFAULT_GROUP.name, "Full Server Tick", null);
     final TimingData minuteData;


```

**Comment by algomaster99** [comment]
@khaes-kth I can have a look at this issue.

**Comment by algomaster99** [comment]
@khaes-kth I inspected this issue and I think it is because of the pretty printer options we use. For example, check this line.

https://github.com/SpoonLabs/sorald/blob/673137680e5d7aae663230d627aaf18316e3cf68/src/main/java/sorald/Repair.java#L295

It adds an option for cleaning imports which can either add or remove the import statements. Do we need this functionality in sorald? Sorald is supposed to sniper print the file with the repairs and it shouldn't concern the import statements if it is not explicitly causing a violation (we will know this because static analyzer will tell us). Please correct me if I am wrong.

I tried removing this option, however, many other tests fail, but I will take a look at it later.

**Comment by khaes-kth** [comment]
> Sorald is supposed to sniper print the file with the repairs and it shouldn't concern the import statements if it is not explicitly causing a violation (we will know this because static analyzer will tell us).

I agree. However, it is possible that a fix requires new imports. Isn't it?

**Comment by algomaster99** [comment]
> However, it is possible that a fix requires new imports.

That's right but we should let the processors deal with it not the pretty printer.

**Comment by khaes-kth** [comment]
> That's right but we should let the processors deal with it not the sniper printer.

Yeah. That's an option to be considered. I'm not sure that it is clearly preferable. Actually, if we have a proper "import-adder" in Spoon that does this automatically, it makes sense to leave this to the pretty-printer instead of having specific import-adders for processors.

**Comment by slarse** [comment]
The printer is not importing anything, it's the preprocessors for the printer (which are processors :) ). The printer itself has nothing to do with importing, it just prints. Sorald has an adapted version of the force import functionality from Spoon, where we try to only add or remove imports for references that have been changed. It's been a year or so since I poked around that part, so I don't remember the details, but you can find it here: https://github.com/SpoonLabs/sorald/blob/master/src/main/java/sorald/SelectiveForceImport.java

You'll have to do some debugging to understand the flow (it's really rather convoluted, but piggybacks on what exists in Spoon instead of reinventing the wheel).

It's undesirable for Sorald's processors themselves to deal with imports, because imports exist on the compilation unit level, which is a compiler construct that is a little finicky to reason about when you have an AST; it doesn't neatly fit in anywhere.

**Comment by slarse** [comment]
As for the bug; when an import is incorrectly added or removed it's probably due to a problem with resolving references, which is common in noclasspath mode.

**Comment by khaes-kth** [comment]
Thanks @slarse . Very helpful comments as always :)

**Comment by algomaster99** [comment]
> You'll have to do some debugging to understand the flow (it's really rather convoluted, but piggybacks on what exists in Spoon instead of reinventing the wheel).

Indeed.

I tried to follow the code from [this line](https://github.com/SpoonLabs/sorald/blob/87ce9cc379184fe141dc6dea98e344f21f461818/src/main/java/sorald/Repair.java#L224). The `cu` in the argument had the correct import statements. However, `printTypes` lead me to this [line](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java#L424), which removes the import statements from the compilation unit. I am also not able to debug what's happening inside the `run` API. Probably, it runs all the preprocessors configured [here](https://github.com/SpoonLabs/sorald/blob/87ce9cc379184fe141dc6dea98e344f21f461818/src/main/java/sorald/Repair.java#L291-L295), but I can't get debug what steps do each preprocessor execute.

**Comment by slarse** [comment]
Just as an FYI, there could also be a bug in how I implemented that thing. As noted, the execution flow for the force importing is reaaaally out there.

@algomaster99  I can't really help with how it works, I don't remember much of it. All I remember is that I had a tough time figuring it out :)

**Comment by algomaster99** [comment]
Thanks @slarse! I will try to figure this out and post a solution or just more updates that might lead us to one.

**Comment by monperrus** [comment]
Closed per https://github.com/INRIA/spoon/pull/4331
