### ISSUE TITLE
Scheduled tests on master is failing

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#612]
The scheduled test have been failing for a while. See for example https://github.com/SpoonLabs/sorald/actions/runs/1427933810

**Comment by algomaster99** [comment]
On just a quick look, 4 tests are failing on `windows-latest` with the error message - `M2_HOME must be initialized to use this MavenLauncher constructor.`. This comes from [this method](https://github.com/INRIA/spoon/blob/6a5c8a1308f7d7199783b359fdb76b51e0f911b2/src/main/java/spoon/support/compiler/SpoonPom.java#L523) and is probably the source of the problem because the mvn is indeed in path otherwise other maven commands in the workflow wouldn't run.
