### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by alexec** [SpoonLabs/sorald#892]
Maven is the defacto build tool for Java. I know some people love Bazel or Gradle, but almost every loves Maven. 

Please can we have either (a) a plugin, or (b) how to run without downloading.

**Comment by algomaster99** [comment]
It has been on our mind to make Sorald's usage as convenient as possible, but we never got to it because of priorities. As of now, Sorald is meant to be used as a CLI tool, and not as an API. However, if you want to use it with maven, you can plugin the spec as suggested [here](https://search.maven.org/artifact/se.kth.castor/sorald/0.6.0/jar). Then you could run sorald as we run it in our tests. We run it as a CLI and capture the STDOUT and files created to test the output. You could see [this test](https://github.com/SpoonLabs/sorald/blob/master/sorald/src/test/java/sorald/miner/WarningMinerTest.java#L47) as an example.

We are presenting [Sorald at EclipseCon 2022](https://www.eclipsecon.org/2022/sessions/let-bot-deal-your-static-analysis-warnings-backlog) and before that we have some todos; one of them being to make its usage as easy as possible. We have some ideas regarding it and we are working on them. I will keep you posted when it is done. Nevertheless, I will update the documentation.

**Comment by algomaster99** [comment]
@alexec Hey! We found time to work on the `maven-plugin` and implemented a first prototype for it. Please run the following command to give it a whirl :)
```
mvn se.kth.castor:sorald:repair -DruleKey=<ruleKey>
```

**Comment by algomaster99** [comment]
The maven-plugin is released and from now on, it will be maintained as well. Hence, closing.

**Comment by monperrus** [comment]
Do we have CD to Maven Central for the maven-plugin? That would be great.

**Comment by algomaster99** [comment]
We do not, as of now. If we have CD, we need to ensure that we deploy releases, not SNAPSHOTs because the latter is not hosted on Maven central. We would need a CD like gumtree-spoon that deploys a release on every commit.
